version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: delivery_postgres
    restart: always
    environment:
      POSTGRES_USER: delivery
      POSTGRES_PASSWORD: delivery123
      POSTGRES_DB: deliverydb
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U delivery -d deliverydb"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - delivery-network
  delivery-api:
    container_name: delivery-api-container
    build: . 
    ports:
      - "8080:8080" 
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/deliverydb
      SPRING_DATASOURCE_USERNAME: delivery
      SPRING_DATASOURCE_PASSWORD: delivery123
      SPRING_PROFILES_ACTIVE: dev
      TZ: America/Sao_Paulo
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - delivery-network

networks:
  delivery-network:
    driver: bridge

volumes:
  postgres_data: